rBlog/config/routes.rb
Rails.application.routes.draw do
  get 'contact' => 'contacts#new'
  get 'contacts/create'
  get 'about' => 'about#index'

  namespace :admin do
    get "login" => "sessions#new", :as => "login"
  end

  namespace :admin do
    get "logout" => "sessions#destroy", :as => "logout"
  end

  namespace :admin do
    get 'sessions/create'
  end

  namespace :admin do
    get 'users/new'
    get 'users/create'
    get 'users/edit'
    get 'users/update'
    get 'users/destroy'
    get 'users/index'
    get 'users/show'
  end
  namespace :admin do
    get 'comments/destroy'
  end
  get 'comments/new'
  namespace :admin do
    get 'categories/new'
    get 'categories/create'
    get 'categories/edit'
    get 'categories/update'
    get 'categories/destroy'
    get 'categories/index'
    get 'categories/show'
  end
  get 'categories/show'
  namespace :admin do
    get 'posts/new'
    get 'posts/create'
    get 'posts/edit'
    get 'posts/update'
    get 'posts/destroy'
    get 'posts/index'
    get 'posts/show'
  end
  get 'posts/index'
  get 'posts/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts, :categories, :comments
  resources "contacts", only: [:new, :create]

  namespace :admin do
    resources :posts, :categories, :comments, :users, :sessions
  end

  resources :posts do
    resources :comments
  end

  root 'posts#index'

end

rBlog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rBlog/app/models/category.rb
class Category < ApplicationRecord
    has_many :posts

    validates :name, presence: true

    def self.search(query)
        where("name like ?" , "%#{query}%")
    end
end

rBlog/app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
end

rBlog/app/models/post.rb
class Post < ApplicationRecord
    belongs_to :category
    belongs_to :user
    has_many :comments

    validates :title, presence: true
    validates :category_id, presence: true
    validates :body, presence: true

    has_attached_file :image , :default_url => ":style/rails1.jpg"
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

    def self.search(query)
        where("title like ? OR body like ?" , "%#{query}%", "%#{query}%")
    end
end

rBlog/app/models/user.rb
class User < ApplicationRecord
    attr_accessor :password
    before_save :encrypt_password

    has_many :posts

    validates :name, presence: true
    validates :email, presence: true
    validates :password, presence: true
    validates :password, confirmation: true

    def self.authenticate(email,password)
        user = find_by_email(email)
        if user && user.password_hash == BCrypt::Engine.hash_secret(password,user.password_salt)
            user
        else
            nil
        end
    end

    def encrypt_password
        if password.present?
            self.password_salt = BCrypt::Engine.generate_salt
            self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
        end
    end

    def self.search(query)
        where("name like ? OR email like ?" , "%#{query}%", "%#{query}%")
    end
end

rBlog/app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

rBlog/app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::ApplicationController
  before_action :verify_logged_in
  def destroy
  end
end

rBlog/app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::ApplicationController
  before_action :verify_logged_in
  def new
    @page_title = 'Add post'
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if params[:post][:image].blank?
      @post.image = nil
    end

    if @post.save
      flash[:notice]="post created"
      redirect_to admin_posts_path
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if params[:post][:image].blank?
      @post.image = nil
    end

    if @post.update(post_params)
      flash[:notice]="post updated"
      redirect_to admin_posts_path
    else
      render 'new'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice]="post deleted"
    redirect_to admin_posts_path
  end

  def index
    if params[:search]
      @posts = Post.search(params[:search]).all.order('created_at DESC').paginate(:per_page => 10, :page => params[:page])
    else
      @posts = Post.all.order('created_at DESC').paginate(:per_page => 10, :page => params[:page])
    end
  end

  def show
  end

  private
  def post_params
    params.require(:post).permit(:title, :category_id, :user_id, :tags, :image, :body)
  end
end

rBlog/app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  before_action :verify_logged_in
  def new
    @page_title = 'Add user'
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice]="user created"
      redirect_to admin_users_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]="user updated"
      redirect_to admin_users_path
    else
      render 'new'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice]="post deleted"
    redirect_to admin_users_path
  end

  def index
    if params[:search]
      @users = User.search(params[:search]).all.order('created_at DESC').paginate(:per_page => 10, :page => params[:page])
    else
      @users = User.all.order('created_at DESC').paginate(:per_page => 10, :page => params[:page])
    end
  end

  def show
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

rBlog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rBlog/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category= Category.find(params[:id])
    @categories= Category.all
    @posts = @category.posts
  end
end

rBlog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    flash[:notice]="comment added"
    redirect_to post_path(@post)
  end
  private
    def comment_params
      params.require(:comment).permit(:name, :email, :body, :post_id)
    end
end

rBlog/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end

  def create
  end
end

rBlog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    if params[:search]
      @posts = Post.search(params[:search]).all.order('created_at DESC').paginate(:per_page => 10, :page => params[:page])
    else
      @posts = Post.all.order('created_at DESC').paginate(:per_page => 10, :page => params[:page])
    end
    @categories = Category.all
  end

  def show
    @post = Post.find(params[:id])
    @categories = Category.all
    @comment = Comment.new
    @comment = Comment.all
  end
end

rBlog/app/helpers/about_helper.rb
module AboutHelper
end

rBlog/app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

rBlog/app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

rBlog/app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

rBlog/app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

rBlog/app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

rBlog/app/helpers/application_helper.rb
module ApplicationHelper
end

rBlog/app/helpers/categories_helper.rb
module CategoriesHelper
end

rBlog/app/helpers/comments_helper.rb
module CommentsHelper
end

rBlog/app/helpers/contacts_helper.rb
module ContactsHelper
end

rBlog/app/helpers/posts_helper.rb
module PostsHelper
end

rBlog/app/views/admin/comments/destroy.html.erb
<h1>Admin::Comments#destroy</h1>
<p>Find me in app/views/admin/comments/destroy.html.erb</p>

rBlog/app/views/admin/posts/edit.html.erb
<script>
	$(function() {
	$('textarea#froala-editor').froalaEditor()
	});
</script>

<h2>edit post</h2>
<%= form_for [:admin, @post] do |f| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class= "alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>

	<div class = "from-group">
		<%= f.label :title %><br/>
		<%= f.text_field :title ,class: 'form-control'%>
	</div>
	<div class = "from-group">
		<%= f.label :category %><br/>
		<%= f.select :category_id,Category.all.collect {|x| [x.name, x.id]}, {:include_blank => 'select one'} ,class: 'form-control'%>
	</div>
	<div class = "from-group">
		<%= f.label :author %><br/>
		<%= f.select :user_id,User.all.collect {|x| [x.name, x.id]}, {:include_blank => 'select one'} ,class: 'form-control'%>
	</div>
	<div class = "from-group">
		<%= f.label :image %>
		<%= f.file_field :image%>
	</div>
	<% if @post.image.exists? %>
		<%= image_tag @post.image.url, width: '100%' %>
	<% end %>
	<div class = "from-group">
		<%= f.label :tags %><br/>
		<%= f.text_area :tags,class: 'form-control'%><br/>
	</div>
	<div class = "from-group">
		<%= f.label :body %><br/>
		<%= f.text_area :body,class: 'form-control' , id: 'froala-editor'%><br/>
	</div>
	<%= f.submit "submit", class:'btn btn-primary' %>
	<%= link_to "cancel", admin_posts_path, class:'btn btn-default' %>

<% end %>

rBlog/app/views/admin/posts/index.html.erb
<h2 class="page-header">Manage posts  <%= link_to "Create New", new_admin_post_path ,class: "btn btn-success" %> </h2>
<%if @posts.exists?%>

    <table class="table table-striped">
        <tr>
            <th> post title </th>
            <th> post category </th>
            <th> date create </th>
            <th>actions</th>
        </tr>
        <% @posts.each do |post| %>
            <tr>
                <td> <%= post.title %> </td>
                <td> <%= post.category.name %>
                <td> <%= post.created_at.to_time.strftime('%B %e at %l:%M %p') %> </td>
                <td> <%= link_to "Edit", edit_admin_post_path(post),class:'btn btn-primary' %> <%= link_to "Delete", admin_post_path(post),class:'btn btn-danger', method: :delete, data: {confirm: 'are you sure?'} %> </td>
            </tr>
        <%end%>
    </table>
    <%= will_paginate @posts %>
<% else %>
    <p> no posts </p>
<% end %>

rBlog/app/views/admin/posts/new.html.erb
<script>
	$(function() {
	$('textarea#froala-editor').froalaEditor()
	});
</script>

<h2>add new post</h2>
<%= form_for [:admin, @post] do |f| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class= "alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>

	<div class = "from-group">
		<%= f.label :title %>
		<%= f.text_field :title ,class: 'form-control'%>
	</div>
	<div class = "from-group">
		<%= f.label :category %>
		<%= f.select :category_id,Category.all.collect {|x| [x.name, x.id]}, {:include_blank => 'select one'} ,class: 'form-control'%>
	</div>
	<div class = "from-group">
		<%= f.label :author %>
		<%= f.select :user_id ,User.all.collect {|x| [x.name, x.id]}, {:include_blank => 'select one'} ,class: 'form-control'%>
	</div>
	<div class = "from-group">
		<%= f.label :image %>
		<%= f.file_field :image%>
	</div>
	<div class = "from-group">
		<%= f.label :tags %>
		<%= f.text_area :tags,class: 'form-control', id: 'froala-editor' %>
	</div>
	<div class = "from-group">
		<%= f.label :body %>
		<%= f.text_area :body,class: 'form-control', id: 'froala-editor' %>
	</div>
	<%= f.submit "submit", class:'btn btn-primary' %>
	<%= link_to "cancel", admin_posts_path, class:'btn btn-default' %>

<% end %>

rBlog/app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

rBlog/app/views/posts/index.html.erb
<div id= "posts-index">
    <%if @posts.exists?%>
        <% @posts.each_slice(5) do |post| %>
            <div class = "row">
                <% @posts.each do |post| %>
                    <div class = "col-md-6">
                        <div class = "post">
                            <%= image_tag post.image.url, width: '100%' %>
                            <div class = "post-content">
                                <h3> <%= post.title %> </h3>
                                <small> Posted by <%= post.user.name %> on <%= post.created_at.to_time.strftime('%B %e at %l:%M %p') %> </small>
                                <%= raw post.body.truncate(200) %>
                                <%= link_to "Read More", post_path(post), class:'btn btn-primary' %>
                            </div>
                        </div>
                    </div>
                <% end %>
            </div>
        <% end %>
    <% else %>
        <p> no post yet </p>
    <%end%>
</div>

rBlog/app/views/posts/show.html.erb
<div class= "well post-single">
    <h2 class="page-header"> <%= @post.title%> </h2>
    <small> Posted by <%= @post.user.name %> on <%= @post.created_at.to_time.strftime('%B %e at %l:%M %p') %> </small>
    <%= image_tag @post.image.url, width: '100%' %>
    <%= raw @post.body %>
</div>

<%= render 'partials/comments' %>