rBlog/config/routes.rb
Rails.application.routes.draw do
  get 'contact' => 'contacts#new'
  get 'contacts/create'
  get 'about' => 'about#index'

  namespace :admin do
    get "login" => "sessions#new", :as => "login"
  end

  namespace :admin do
    get "logout" => "sessions#destroy", :as => "logout"
  end

  namespace :admin do
    get 'sessions/create'
  end

  namespace :admin do
    get 'users/new'
    get 'users/create'
    get 'users/edit'
    get 'users/update'
    get 'users/destroy'
    get 'users/index'
    get 'users/show'
  end
  namespace :admin do
    get 'comments/destroy'
  end
  get 'comments/new'
  namespace :admin do
    get 'categories/new'
    get 'categories/create'
    get 'categories/edit'
    get 'categories/update'
    get 'categories/destroy'
    get 'categories/index'
    get 'categories/show'
  end
  get 'categories/show'
  namespace :admin do
    get 'posts/new'
    get 'posts/create'
    get 'posts/edit'
    get 'posts/update'
    get 'posts/destroy'
    get 'posts/index'
    get 'posts/show'
  end
  get 'posts/index'
  get 'posts/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts, :categories, :comments
  resources "contacts", only: [:new, :create]

  namespace :admin do
    resources :posts, :categories, :comments, :users, :sessions
  end

  resources :posts do
    resources :comments
  end

  root 'posts#index'

end

rBlog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rBlog/app/models/category.rb
class Category < ApplicationRecord
    has_many :posts

    validates :name, presence: true

    def self.search(query)
        where("name like ?" , "%#{query}%")
    end
end

rBlog/app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
end

rBlog/app/models/post.rb
class Post < ApplicationRecord
    belongs_to :category
    belongs_to :user
    has_many :comments

    validates :title, presence: true
    validates :category_id, presence: true
    validates :body, presence: true

    has_attached_file :image , :default_url => ":style/rails1.jpg"
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

    def self.search(query)
        where("title like ? OR body like ?" , "%#{query}%", "%#{query}%")
    end
end

rBlog/app/models/user.rb
class User < ApplicationRecord
    attr_accessor :password
    before_save :encrypt_password

    has_many :posts

    validates :name, presence: true
    validates :email, presence: true
    validates :password, presence: true
    validates :password, confirmation: true

    def self.authenticate(email,password)
        user = find_by_email(email)
        if user && user.password_hash == BCrypt::Engine.hash_secret(password,user.password_salt)
            user
        else
            nil
        end
    end

    def encrypt_password
        if password.present?
            self.password_salt = BCrypt::Engine.generate_salt
            self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
        end
    end

    def self.search(query)
        where("name like ? OR email like ?" , "%#{query}%", "%#{query}%")
    end
end

rBlog/app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

rBlog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rBlog/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category= Category.find(params[:id])
    @categories= Category.all
    @posts = @category.posts
  end
end

rBlog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    flash[:notice]="comment added"
    redirect_to post_path(@post)
  end
  private
    def comment_params
      params.require(:comment).permit(:name, :email, :body, :post_id)
    end
end

rBlog/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end

  def create
  end
end

rBlog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    if params[:search]
      @posts = Post.search(params[:search]).all.order('created_at DESC').paginate(:per_page => 10, :page => params[:page])
    else
      @posts = Post.all.order('created_at DESC').paginate(:per_page => 10, :page => params[:page])
    end
    @categories = Category.all
  end

  def show
    @post = Post.find(params[:id])
    @categories = Category.all
    @comment = Comment.new
    @comment = Comment.all
  end
end

rBlog/app/helpers/about_helper.rb
module AboutHelper
end

rBlog/app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

rBlog/app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

rBlog/app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

rBlog/app/helpers/application_helper.rb
module ApplicationHelper
end

rBlog/app/helpers/categories_helper.rb
module CategoriesHelper
end

rBlog/app/helpers/comments_helper.rb
module CommentsHelper
end

rBlog/app/helpers/contacts_helper.rb
module ContactsHelper
end

rBlog/app/helpers/posts_helper.rb
module PostsHelper
end

rBlog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top ">
    <a class="navbar-brand" href="#">rBlog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Home", root_path,class:"nav-link" %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="about.html">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="contact.html">Contact</a>
        </li>
      </ul>
      <%= render 'partials/search' %>
    </div>
  </nav>
    <section>
      <br/>
      <br/>
      <br/>
      <div class="container">
        <div class="row">
          <div class="col-md-8">
            <% if flash[:notice] %>
              <div class="alert alert-success"><%= flash[:notice] %>
            <% end %>
            <% if flash[:alert] %>
              <div class="alert alert-success"><%= flash[:alert] %>
            <% end %>
            <%= yield %>
          </div>
          <div class="col-md-4">
            <%= render 'partials/sidebar' %>
          </div>
        </div>
      </div>
    </section>
      <%= render 'partials/footer'%>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="/javascripts/bootstrap.js"></script>
  </body>
</html>

rBlog/app/views/partials/admin/_search.html.erb
<% if params[:controller] == 'admin/posts' %>
    <%= form_tag(admin_posts_path, :method => "get", id:"search-form", class:"search-form pull-right") do %>
        <div class= "form-group">
            <%= text_field_tag :search, params[:search], placeholder: "Search Posts" ,class:'form-control' %>
        </div>
        <%= submit_tag "search", :name => nil, class: 'btn btn-primary' %>
    <% end %>
<% elsif params[:controller] == 'admin/categories' %>
    <%= form_tag(admin_categories_path, :method => "get", id:"search-form", class:"search-form pull-right") do %>
        <div class= "form-group">
            <%= text_field_tag :search, params[:search], placeholder: "Search categories" ,class:'form-control' %>
        </div>
        <%= submit_tag "search", :name => nil, class: 'btn btn-primary' %>
    <% end %>
<% elsif params[:controller] == 'admin/users' %>
    <%= form_tag(admin_users_path, :method => "get", id:"search-form", class:"search-form pull-right") do %>
        <div class= "form-group">
            <%= text_field_tag :search, params[:search], placeholder: "Search users" ,class:'form-control' %>
        </div>
        <%= submit_tag "search", :name => nil, class: 'btn btn-primary' %>
    <% end %>
<%end%>